import { expect, Locator, Page } from '@playwright/test';
import { BasePage } from '../core/BasePage';
import path from 'path';

export class PIMPage extends BasePage {
  pimMenu!: Locator;
  pimHeader!: Locator;
  employeeInfoHeader!: Locator;
  addEmployeeHeader!: Locator;
  addEmployeeButton!: Locator;
  saveButton!: Locator;
  firstNameInput!: Locator;
  middleNameInput!: Locator;
  lastNameInput!: Locator;
  employeeIdInput!: Locator;
  profileUploadInput!: Locator;
  profileAddIcon!: Locator;
  successToast!: Locator;
  employeeNameSearchInput!: Locator;
  employeeIdSearchInput!: Locator;
  searchButton!: Locator;
  tableRows!: Locator;
  firstRowEmployeeId!: Locator;
  firstRowEmployeeName!: Locator;
  static createdEmpId: string;
  static createdEmpFullName: string;
  static empIdCounter = 1; 
  static createdEmpFirstMiddle: string;
  static createdEmpLastName: string;
  tableContainer!: Locator;
  static updatedJobTitle: string;
 static updatedEmploymentStatus: string;
gridEmpId!: Locator;
gridFirstMiddleName!: Locator;
gridLastName!: Locator;
gridJobTitle!: Locator;
gridEmploymentStatus!: Locator;
deleteConfirmButton!: Locator;
deletePopupHeading!: Locator;
deletePopupMessage!: Locator;
confirmDeleteButton!: Locator;
noRecordsFoundText!: Locator;
  constructor(page: Page) {
    super(page);
    this.pimMenu = page.locator("//span[text()='PIM']");
    this.pimHeader = page.locator("//h6[text()='PIM']");
    this.employeeInfoHeader = page.locator("//h5[text()='Employee Information']");
    this.addEmployeeHeader = page.locator("//h6[text()='Add Employee']");
    this.addEmployeeButton = page.getByRole('button', { name: 'Add' });
    this.saveButton = page.getByRole('button', { name: 'Save' });
    this.firstNameInput = page.locator("input[name='firstName']");
    this.middleNameInput = page.locator("input[name='middleName']");
    this.lastNameInput = page.locator("input[name='lastName']");
    this.employeeIdInput = page.locator("//label[normalize-space()='Employee Id']/ancestor::div[contains(@class,'oxd-input-group')]//input");
    this.profileUploadInput = page.locator("input[type='file']");
    this.profileAddIcon = page.locator("button.employee-image-action");
    this.successToast = page.locator("div.oxd-toast--success");
    this.employeeNameSearchInput = page.locator("div.oxd-autocomplete-text-input input");
    this.employeeIdSearchInput = page.locator("//label[text()='Employee Id']/ancestor::div[contains(@class,'oxd-input-group')]//input");
    this.searchButton = page.getByRole('button', { name: 'Search' });
    this.tableRows = page.locator("div.oxd-table-body > div.oxd-table-row");
    this.firstRowEmployeeId = page.locator( "div.oxd-table-row div.oxd-table-cell:nth-child(2) div");
    this.firstRowEmployeeName = page.locator("div.oxd-table-row div.oxd-table-cell:nth-child(3) div");
    this.tableContainer = page.locator('div.orangehrm-container');this.tableRows = page.locator('div.oxd-table-body div.oxd-table-row');
    this.tableRows = page.locator('div.oxd-table-body > div.oxd-table-row');
    this.gridEmpId = page.locator('div.oxd-table-row div.oxd-table-cell:nth-child(2) div');
    this.gridFirstMiddleName = page.locator('div.oxd-table-row div.oxd-table-cell:nth-child(3) div');
    this.gridLastName = page.locator('div.oxd-table-row div.oxd-table-cell:nth-child(4) div');
    this.gridJobTitle = page.locator('div.oxd-table-row div.oxd-table-cell:nth-child(5) div');
    this.gridEmploymentStatus = page.locator('div.oxd-table-row div.oxd-table-cell:nth-child(6) div');
    this.deletePopupHeading = page.locator('p.oxd-text--card-title');
    this.deletePopupMessage = page.locator('p.oxd-text--card-body');
    this.confirmDeleteButton = page.getByRole('button', {name: 'Yes, Delete'});
    this.noRecordsFoundText = page.locator('div.orangehrm-horizontal-padding span.oxd-text--span');

  }

  async clickPIM(): Promise<void> {
    await this.pimMenu.click();
  }

  async verifyPIMPage(): Promise<void> {
    await expect(this.pimHeader).toBeVisible();
    await expect(this.employeeInfoHeader).toBeVisible();
  }

  async openAddEmployee(): Promise<void> {
    await this.addEmployeeButton.click();
    await expect(this.addEmployeeHeader).toBeVisible();
  }

async enterPersonalDetails(data: any): Promise<void> {
  const { firstName, middleName, lastName } = data.personalDetails;
  await this.firstNameInput.fill(firstName);
  await this.middleNameInput.fill(middleName);
  await this.lastNameInput.fill(lastName);
  PIMPage.createdEmpFullName = `${firstName} ${middleName} ${lastName}`.trim();
  const systemEmpId = (await this.employeeIdInput.inputValue())?.trim();
  if (!systemEmpId) {
    throw new Error('Employee ID was not auto-generated by system');
  }
  const nextEmpId = this.generateNextEmpId(systemEmpId);
  await this.employeeIdInput.fill('');
  await this.employeeIdInput.type(nextEmpId, { delay: 50 });
  PIMPage.createdEmpId = nextEmpId;
}

private generateNextEmpId(currentId: string): string {
  const trimmedId = currentId.trim();
  if (/^\d+$/.test(trimmedId)) {
    const nextNumber = parseInt(trimmedId, 10) + 1;
    return nextNumber.toString().padStart(trimmedId.length, '0');
  }
  const match = trimmedId.match(/^([A-Z]+)(\d+)$/);
  if (!match) {
    throw new Error(`Invalid Employee ID format: ${trimmedId}`);
  }
  const prefix = match[1];     
  const numericPart = match[2];
  const number = parseInt(numericPart, 10);
  if (number >= 10 && number < 100) {
    return `${prefix}01${number + 1}`;
  }
  const nextNumber = number + 1;
  return `${prefix}${nextNumber.toString().padStart(numericPart.length, '0')}`;
}


  async uploadProfilePicture(): Promise<void> {
    const imagePath = path.join(process.cwd(), 'src', 'assets', 'profile.jpg');
    await this.profileUploadInput.setInputFiles(imagePath);
  }

 async saveEmployee(): Promise<void> {
  await this.saveButton.waitFor({ state: 'visible' });
  await this.saveButton.click();
}

  async verifyEmployeeCreated(): Promise<void> {
  const toast = this.page.locator('div.oxd-toast--success');
  //await toast.waitFor({ state: 'visible', timeout: 15000 });
}

async searchEmployee(): Promise<void> {
  await this.employeeIdSearchInput.waitFor({ state: 'visible' });
  await this.employeeIdSearchInput.fill(PIMPage.createdEmpId);
  await this.searchButton.click();
}

async verifySingleResult(): Promise<void> {
  const matchingRows = this.page.locator(`div.oxd-table-row:has(div:has-text("${PIMPage.createdEmpId}"))`);
  await matchingRows.first().scrollIntoViewIfNeeded();
  const count = await matchingRows.count();
  expect(count).toBe(1);
}

async verifyEmployeeDetailsInGrid(): Promise<void> {
  const firstRow = this.tableRows.first();
  await firstRow.scrollIntoViewIfNeeded();
  const actualEmpId = (await this.firstRowEmployeeId.textContent())?.trim();
  const actualEmpName = (await this.firstRowEmployeeName.textContent())?.trim();
  expect(actualEmpId).toBe(PIMPage.createdEmpId);
  expect(actualEmpName).toBe(PIMPage.createdEmpFullName);
}

private incrementEmpId(empId: string): string {
  const match = empId.match(/(\d+)$/);
  if (!match) {
    return `${empId}1`;
  }
  const number = match[1];
  const prefix = empId.slice(0, empId.length - number.length);
  return `${prefix}${parseInt(number, 10) + 1}`;
}
private async getTrimmedText(locator: Locator): Promise<string> {
  await locator.waitFor({ state: 'visible', timeout: 10000 });
  const text = await locator.textContent();
  return (text ?? '').trim();
}

private async scrollIntoView(locator: Locator): Promise<void> {
  await locator.scrollIntoViewIfNeeded();
  await locator.waitFor({ state: 'visible', timeout: 10000 });
}

async clickEditByEmployeeId(): Promise<void> {
  const row = this.page.locator(`div.oxd-table-row:has(div:has-text("${PIMPage.createdEmpId}"))`);
  await row.scrollIntoViewIfNeeded();
  await row.locator('button:has(i.bi-pencil-fill)').click();
}

async openJobTab(): Promise<void> {
  const jobTab = this.page.locator('a.orangehrm-tabs-item[href*="viewJobDetails"]');
  await jobTab.click();
}

async selectDropdownByLabel(label: string, option: string): Promise<void> {
  const dropdown = this.page.locator(`//label[normalize-space()="${label}"]/ancestor::div[contains(@class,"oxd-input-group")]//div[contains(@class,"oxd-select-text-input")]`);
  await dropdown.click();
  const optionLocator = this.page.locator(`//div[@role="listbox"]//span[normalize-space()="${option}"]`);
  await optionLocator.click();
}

async updateJobDetails(jobTitle: string, employmentStatus: string): Promise<void> {
  await this.selectDropdownByLabel('Job Title', jobTitle);
  await this.selectDropdownByLabel('Employment Status', employmentStatus);
  PIMPage.updatedJobTitle = jobTitle;
  PIMPage.updatedEmploymentStatus = employmentStatus;
}

async saveJobDetails(): Promise<void> {
  await this.page.getByRole('button', { name: 'Save' }).click();
}

async verifyUpdateSuccess(): Promise<void> {
  await this.page.locator('div.oxd-toast--success').waitFor({ state: 'visible', timeout: 10000 });
}

async verifyUpdatedJobDetailsInGrid(): Promise<void> {
  const row = this.page.locator(`div.oxd-table-row:has(div:has-text("${PIMPage.createdEmpId}"))`);
  await row.waitFor({ state: 'visible', timeout: 15000 });
  const empId = (await row.locator('div.oxd-table-cell:nth-child(2) div').textContent())?.trim();
  const firstMiddle = (await row.locator('div.oxd-table-cell:nth-child(3) div').textContent())?.trim();
  const lastName = (await row.locator('div.oxd-table-cell:nth-child(4) div').textContent())?.trim();
  const jobTitle = (await row.locator('div.oxd-table-cell:nth-child(5) div').textContent())?.trim();
  const employmentStatus = (await row.locator('div.oxd-table-cell:nth-child(6) div').textContent())?.trim();
  expect(empId).toBe(PIMPage.createdEmpId);
  expect(`${firstMiddle} ${lastName}`.trim()).toBe(PIMPage.createdEmpFullName);
  expect(jobTitle).toBe(PIMPage.updatedJobTitle);
  expect(employmentStatus).toBe(PIMPage.updatedEmploymentStatus);
}

async openEmployeeForEdit(): Promise<void> {
  const row = this.page.locator(`div.oxd-table-row:has(div:has-text("${PIMPage.createdEmpId}"))`);
  await row.scrollIntoViewIfNeeded();
  const editButton = row.locator('button:has(i.bi-pencil-fill)');
  await editButton.click();
}

 async clickSearch(): Promise<void> {
    await this.searchButton.click();
  }

  async clickDeleteIconByEmployeeId(): Promise<void> {
  const row = this.page.locator(`div.oxd-table-row:has(div:has-text("${PIMPage.createdEmpId}"))`);
  const deleteIcon = row.locator('button:has(i.bi-trash)');
  await deleteIcon.click();
}

async verifyDeletePopupHeading(expectedHeading: string): Promise<void> {
  await this.deletePopupHeading.waitFor({ state: 'visible', timeout: 10000 });
  const actualHeading = (await this.deletePopupHeading.textContent())?.trim();
  expect(actualHeading).toBe(expectedHeading);
}

async verifyPermanentDeleteMessage(): Promise<void> {
  await this.deletePopupMessage.waitFor({ state: 'visible', timeout: 10000 });
  const actualText = (await this.deletePopupMessage.textContent())?.trim();
  expect(actualText).toBe('The selected record will be permanently deleted. Are you sure you want to continue?');
}

async confirmDeleteEmployee(): Promise<void> {
  await this.confirmDeleteButton.waitFor({ state: 'visible', timeout: 10000 });
  await this.confirmDeleteButton.click();
}

async verifyDeleteSuccessToast(): Promise<void> {
  await this.successToast.waitFor({ state: 'visible', timeout: 10000 });
}

async verifyNoRecordsFoundInGrid(): Promise<void> {
  await this.noRecordsFoundText.waitFor({ state: 'visible', timeout: 10000 });
  const actualText = (await this.noRecordsFoundText.textContent())?.trim();
  expect(actualText).toBe('No Records Found');
}

}

